"""Data models for VoiceOps deep engineering agent analysis."""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import uuid4
from pydantic import BaseModel, Field

from app.analysis.evidence import SDLObservation, TimingDelta


class AnomalyFinding(BaseModel):
    """Structured anomaly finding for agent report."""

    severity: str
    timestamp: str
    protocol: str
    description: str
    evidence: str
    impact: str
    likely_location: str
    confidence: str


class RootCauseFinding(BaseModel):
    """Evidence-driven root cause determination."""

    has_root_cause: bool = False
    root_cause: Optional[str] = None
    evidence: List[str] = Field(default_factory=list)
    confidence: str = "Low"  # High, Medium, Low
    missing_evidence: Optional[str] = None
    facts: List[str] = Field(default_factory=list)
    correlations: List[str] = Field(default_factory=list)
    inferences: List[str] = Field(default_factory=list)
    hypotheses: List[str] = Field(default_factory=list)


class AgentAnalysisResult(BaseModel):
    """Comprehensive 8-section engineering analysis generated by VoiceOps Agent."""

    analysis_id: str = Field(default_factory=lambda: f"analysis_{uuid4().hex[:8]}")
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    trace_ids: List[str] = Field(default_factory=list)
    source_files: List[str] = Field(default_factory=list)
    model_provider: str = "VoiceOps-DeepReasoning-Engine"
    analysis_version: str = "1.0.0"

    # Call-scoped summary metadata
    call_id: Optional[str] = None
    calling_number: Optional[str] = None
    called_number: Optional[str] = None
    start_time_ist: Optional[str] = None
    end_time_ist: Optional[str] = None
    duration: Optional[str] = None

    # Section 1: Executive Summary
    executive_summary: str = Field(..., description="High-level engineering explanation of the call trace")

    # Section 2: Detected Architecture
    architecture_name: str = Field(...)
    architecture_flow: str = Field(...)
    architecture_evidence: List[str] = Field(default_factory=list)
    architecture_confidence: str = "High"

    # Section 3: Call Flow
    call_flow: List[str] = Field(default_factory=list, description="Chronological sequence with timestamps")

    # Section 4: Signaling Analysis
    signaling_analysis: Dict[str, List[str]] = Field(default_factory=dict, description="Observed messages per protocol")

    # Section 5: CUCM SDL Analysis
    sdl_analysis: List[SDLObservation] = Field(default_factory=list)

    # Section 6: Timing Analysis
    timing_analysis: List[TimingDelta] = Field(default_factory=list)

    # Section 7: Anomaly Analysis
    anomaly_analysis: List[AnomalyFinding] = Field(default_factory=list)

    # Section 8: Root Cause / Most Likely Cause
    root_cause_analysis: RootCauseFinding = Field(...)

    # Full Formatted Markdown Report
    markdown_report: str = Field("", description="Complete 8-section markdown report")

    @property
    def summary_markdown(self) -> str:
        return self.markdown_report

